version: '3.8'

services:
  # Servicio de PostgreSQL
  postgres:
    image: postgres:17
    container_name: my_postgres_db
    restart: always
    secrets:
      - db-password
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_DB: L2_Real_State
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

  # Servicio de tu aplicación Spring Boot
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_spring_app
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/L2_Real_State
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: Changazion123  # Se debe utilizar el mismo archivo secreto
    ports:
      - "8080:8080"
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - my_network

volumes:
  pgdata:

networks:
  my_network:

secrets:
  db-password:
    file: db/password.txt
